// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-XTEHLm6xATmJDEdrDQk3i0_cSCi8XPw',
    appId: '1:19253494417:web:cbb6afd1d55d69b00f3530',
    messagingSenderId: '19253494417',
    projectId: 'labactivity3-fab9b',
    authDomain: 'labactivity3-fab9b.firebaseapp.com',
    storageBucket: 'labactivity3-fab9b.appspot.com',
    measurementId: 'G-LWYXRGLFQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAms5J54O1RIfWSxUNF6K4f0JjvFWmcA0M',
    appId: '1:19253494417:android:93324bb4aefcb0da0f3530',
    messagingSenderId: '19253494417',
    projectId: 'labactivity3-fab9b',
    storageBucket: 'labactivity3-fab9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIIyO_xckzCad8ZmZwGX8fXmD12Kxf44g',
    appId: '1:19253494417:ios:c0500560ec3d1e560f3530',
    messagingSenderId: '19253494417',
    projectId: 'labactivity3-fab9b',
    storageBucket: 'labactivity3-fab9b.appspot.com',
    iosBundleId: 'com.example.basicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIIyO_xckzCad8ZmZwGX8fXmD12Kxf44g',
    appId: '1:19253494417:ios:c0500560ec3d1e560f3530',
    messagingSenderId: '19253494417',
    projectId: 'labactivity3-fab9b',
    storageBucket: 'labactivity3-fab9b.appspot.com',
    iosBundleId: 'com.example.basicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-XTEHLm6xATmJDEdrDQk3i0_cSCi8XPw',
    appId: '1:19253494417:web:00cd996152e93c630f3530',
    messagingSenderId: '19253494417',
    projectId: 'labactivity3-fab9b',
    authDomain: 'labactivity3-fab9b.firebaseapp.com',
    storageBucket: 'labactivity3-fab9b.appspot.com',
    measurementId: 'G-MFCB8B9BQ6',
  );

}